#!/bin/bash
set -e

sudo apt update

echo "Installing desktop environment..."
sudo apt -y install \
sway \
swayidle \
swaylock \
swaybg \
xwayland \
dbus-bin \
autotiling \
alacritty \
tofi \
waybar \
firefox-esr \
mako-notifier \
wl-clipboard \
brightnessctl \
fonts-inconsolata \
fonts-font-awesome

echo "Installing audio stack..."
sudo apt -y install \
pipewire \
pipewire-pulse \
wireplumber

echo "Done."
