#!/bin/bash
set -e

sudo apt update

echo "Installing desktop environment..."
sudo apt -y install \
sway \
swaybg \
swayidle \
xwayland \
dbus-bin \
dbus-x11 \
autotiling \
alacritty \
tofi \
waybar \
mako-notifier \
wl-clipboard \
brightnessctl \
fonts-inconsolata \
fonts-font-awesome

echo "Installing audio stack..."
sudo apt -y install \
pipewire \
pipewire-pulse \
wireplumber

echo "Enabling audio services..."
systemctl --user enable --now pipewire pipewire-pulse wireplumber

echo "Granting brightness control to the video group..."
sudo install -m 644 etc/udev/rules.d/90-backlight.rules /etc/udev/rules.d/90-backlight.rules
sudo udevadm control --reload-rules
sudo udevadm trigger --subsystem-match=backlight
sudo usermod -aG video "$USER"
echo "Added $USER to the video group - log out and back in for brightnessctl to work without sudo."

echo "Done."
